// Generated by CoffeeScript 1.12.7
(function () {
  var Notification,
    NotificationElement,
    NotificationIssue,
    UserUtils,
    fs,
    generateException,
    generateFakeFetchResponses,
    path,
    ref,
    temp;

  fs = require("@lumine-code/fs-plus");

  path = require("path");

  temp = require("@lumine-code/temp").track();

  Notification = require("lumine").Notification;

  NotificationElement = require("../lib/notification-element");

  NotificationIssue = require("../lib/notification-issue");

  UserUtils = require("../lib/user-utilities");

  ((ref = require("./helper")),
    (generateFakeFetchResponses = ref.generateFakeFetchResponses),
    (generateException = ref.generateException));

  describe("Notifications", function () {
    var activationPromise, ref1, workspaceElement;
    ((ref1 = []), (workspaceElement = ref1[0]), (activationPromise = ref1[1]));
    beforeEach(async () => {
      workspaceElement = lumine.views.getView(lumine.workspace);
      lumine.notifications.clear();
      activationPromise = lumine.packages.activatePackage("notifications");
      await activationPromise;
    });
    describe("when the package is activated", function () {
      return it("attaches an lumine-notifications element to the dom", function () {
        return expect(workspaceElement.querySelector("lumine-notifications")).toBeDefined();
      });
    });
    describe("when there are notifications before activation", function () {
      beforeEach(async () => {
        await Promise.resolve(lumine.packages.deactivatePackage("notifications"));
      });
      return it("displays all non displayed notifications", async () => {
        var error, warning;
        warning = new Notification("warning", "Un-displayed warning");
        error = new Notification("error", "Displayed error");
        error.setDisplayed(true);
        lumine.notifications.addNotification(error);
        lumine.notifications.addNotification(warning);
        activationPromise = lumine.packages.activatePackage("notifications");
        await activationPromise;
        var notification, notificationContainer;
        notificationContainer = workspaceElement.querySelector("lumine-notifications");
        notification = notificationContainer.querySelector("lumine-notification.warning");
        expect(notification).toExist();
        notification = notificationContainer.querySelector("lumine-notification.error");
        return expect(notification).not.toExist();
      });
    });
    return describe("when notifications are added to lumine.notifications", function () {
      var notificationContainer;
      notificationContainer = null;
      beforeEach(function () {
        var enableInitNotification;
        enableInitNotification = lumine.notifications.addSuccess(
          "A message to trigger initialization",
          {
            dismissable: true,
          },
        );
        enableInitNotification.dismiss();
        advanceClock(NotificationElement.prototype.visibilityDuration);
        advanceClock(NotificationElement.prototype.animationDuration);
        notificationContainer = workspaceElement.querySelector("lumine-notifications");
        jasmine.attachToDOM(workspaceElement);
        return generateFakeFetchResponses();
      });
      it("adds an lumine-notification element to the container with a class corresponding to the type", function () {
        var notification;
        expect(notificationContainer.childNodes.length).toBe(0);
        lumine.notifications.addSuccess("A message");
        notification = notificationContainer.querySelector("lumine-notification.success");
        expect(notificationContainer.childNodes.length).toBe(1);
        expect(notification).toHaveClass("success");
        expect(notification.querySelector(".message").textContent.trim()).toBe("A message");
        expect(notification.querySelector(".meta")).not.toBeVisible();
        lumine.notifications.addInfo("A message");
        expect(notificationContainer.childNodes.length).toBe(2);
        expect(notificationContainer.querySelector("lumine-notification.info")).toBeDefined();
        lumine.notifications.addWarning("A message");
        expect(notificationContainer.childNodes.length).toBe(3);
        expect(notificationContainer.querySelector("lumine-notification.warning")).toBeDefined();
        lumine.notifications.addError("A message");
        expect(notificationContainer.childNodes.length).toBe(4);
        expect(notificationContainer.querySelector("lumine-notification.error")).toBeDefined();
        lumine.notifications.addFatalError("A message");
        expect(notificationContainer.childNodes.length).toBe(5);
        expect(notificationContainer.querySelector("lumine-notification.fatal")).toBeDefined();
        lumine.notifications.addHint("A message");
        expect(notificationContainer.childNodes.length).toBe(6);
        const hint = notificationContainer.querySelector("lumine-notification.hint");
        expect(hint).toHaveClass("icon-light-bulb");
        // A hint asks nothing of the user, so it autohides like any other
        // notification left non-dismissable.
        return expect(hint).not.toHaveClass("has-close");
      });
      it("displays notification with a detail when a detail is specified", function () {
        var notification;
        lumine.notifications.addInfo("A message", {
          detail: "Some detail",
        });
        notification = notificationContainer.childNodes[0];
        expect(notification.querySelector(".detail").textContent).toContain("Some detail");
        lumine.notifications.addInfo("A message", {
          detail: null,
        });
        notification = notificationContainer.childNodes[1];
        expect(notification.querySelector(".detail")).not.toBeVisible();
        lumine.notifications.addInfo("A message", {
          detail: 1,
        });
        notification = notificationContainer.childNodes[2];
        expect(notification.querySelector(".detail").textContent).toContain("1");
        lumine.notifications.addInfo("A message", {
          detail: {
            something: "ok",
          },
        });
        notification = notificationContainer.childNodes[3];
        expect(notification.querySelector(".detail").textContent).toContain("Object");
        lumine.notifications.addInfo("A message", {
          detail: ["cats", "ok"],
        });
        notification = notificationContainer.childNodes[4];
        return expect(notification.querySelector(".detail").textContent).toContain("cats,ok");
      });
      it("does not add the has-stack class if a stack is provided without any detail", function () {
        var notificationElement;
        lumine.notifications.addInfo("A message", {
          stack: "Some stack",
        });
        notificationElement = notificationContainer.querySelector("lumine-notification.info");
        return expect(notificationElement).not.toHaveClass("has-stack");
      });
      it("renders the message as sanitized markdown", function () {
        var notification;
        lumine.notifications.addInfo("test <b>html</b> <iframe>but sanitized</iframe>");
        notification = notificationContainer.childNodes[0];
        return expect(notification.querySelector(".message").innerHTML).toContain(
          "test <b>html</b> ",
        );
      });
      describe("when a dismissable notification is added", function () {
        it("is removed when Notification::dismiss() is called", function () {
          var notification, notificationElement;
          notification = lumine.notifications.addSuccess("A message", {
            dismissable: true,
          });
          notificationElement = notificationContainer.querySelector("lumine-notification.success");
          expect(notificationContainer.childNodes.length).toBe(1);
          notification.dismiss();
          advanceClock(NotificationElement.prototype.visibilityDuration);
          expect(notificationElement).toHaveClass("remove");
          advanceClock(NotificationElement.prototype.animationDuration);
          return expect(notificationContainer.childNodes.length).toBe(0);
        });
        it("is removed when the close icon is clicked", async () => {
          jasmine.attachToDOM(workspaceElement);
          await lumine.workspace.open();
          var notificationElement;
          lumine.notifications.addSuccess("A message", {
            dismissable: true,
          });
          notificationElement = notificationContainer.querySelector("lumine-notification.success");
          expect(notificationContainer.childNodes.length).toBe(1);
          notificationElement.focus();
          notificationElement.querySelector(".close.icon").click();
          advanceClock(NotificationElement.prototype.visibilityDuration);
          expect(notificationElement).toHaveClass("remove");
          advanceClock(NotificationElement.prototype.animationDuration);
          return expect(notificationContainer.childNodes.length).toBe(0);
        });
        it("is removed when core:cancel is triggered", function () {
          var notificationElement;
          lumine.notifications.addSuccess("A message", {
            dismissable: true,
          });
          notificationElement = notificationContainer.querySelector("lumine-notification.success");
          expect(notificationContainer.childNodes.length).toBe(1);
          lumine.commands.dispatch(workspaceElement, "core:cancel");
          advanceClock(NotificationElement.prototype.visibilityDuration * 3);
          expect(notificationElement).toHaveClass("remove");
          advanceClock(NotificationElement.prototype.animationDuration * 3);
          return expect(notificationContainer.childNodes.length).toBe(0);
        });
        return it("focuses the active pane only if the dismissed notification has focus", async () => {
          jasmine.attachToDOM(workspaceElement);
          await lumine.workspace.open();
          var notification1, notificationElement2;
          notification1 = lumine.notifications.addSuccess("First message", {
            dismissable: true,
          });
          lumine.notifications.addError("Second message", {
            dismissable: true,
          });
          notificationElement2 = notificationContainer.querySelector("lumine-notification.error");
          expect(notificationContainer.childNodes.length).toBe(2);
          notificationElement2.focus();
          notification1.dismiss();
          advanceClock(NotificationElement.prototype.visibilityDuration);
          advanceClock(NotificationElement.prototype.animationDuration);
          expect(notificationContainer.childNodes.length).toBe(1);
          expect(notificationElement2).toHaveFocus();
          notificationElement2.querySelector(".close.icon").click();
          advanceClock(NotificationElement.prototype.visibilityDuration);
          advanceClock(NotificationElement.prototype.animationDuration);
          expect(notificationContainer.childNodes.length).toBe(0);
          return expect(lumine.views.getView(lumine.workspace.getActiveTextEditor())).toHaveFocus();
        });
      });
      describe("when an autoclose notification is added", function () {
        var model, notification, ref2;
        ((ref2 = []), (notification = ref2[0]), (model = ref2[1]));
        beforeEach(function () {
          model = lumine.notifications.addSuccess("A message");
          return (notification = notificationContainer.querySelector(
            "lumine-notification.success",
          ));
        });
        it("closes and removes the message after a given amount of time", function () {
          expect(notification).not.toHaveClass("remove");
          advanceClock(NotificationElement.prototype.visibilityDuration);
          expect(notification).toHaveClass("remove");
          expect(notificationContainer.childNodes.length).toBe(1);
          advanceClock(NotificationElement.prototype.animationDuration);
          return expect(notificationContainer.childNodes.length).toBe(0);
        });
        return describe("when the notification is clicked", function () {
          beforeEach(function () {
            return notification.click();
          });
          it("makes the notification dismissable", function () {
            expect(notification).toHaveClass("has-close");
            advanceClock(NotificationElement.prototype.visibilityDuration);
            return expect(notification).not.toHaveClass("remove");
          });
          return it("removes the notification when dismissed", function () {
            model.dismiss();
            return expect(notification).toHaveClass("remove");
          });
        });
      });
      describe("when the default timeout setting is changed", function () {
        var notification;
        notification = [][0];
        beforeEach(function () {
          lumine.config.set("notifications.defaultTimeout", 1000);
          lumine.notifications.addSuccess("A message");
          return (notification = notificationContainer.querySelector(
            "lumine-notification.success",
          ));
        });
        return it("uses the setting value for the autoclose timeout", function () {
          expect(notification).not.toHaveClass("remove");
          advanceClock(1000);
          return expect(notification).toHaveClass("remove");
        });
      });
      describe("when the `description` option is used", function () {
        return it("displays the description text in the .description element", function () {
          var notification;
          lumine.notifications.addSuccess("A message", {
            description: "This is [a link](https://example.com)",
          });
          notification = notificationContainer.querySelector("lumine-notification.success");
          expect(notification).toHaveClass("has-description");
          expect(notification.querySelector(".meta")).toBeVisible();
          expect(notification.querySelector(".description").textContent.trim()).toBe(
            "This is a link",
          );
          return expect(notification.querySelector(".description a").href).toBe(
            "https://example.com/",
          );
        });
      });
      describe("when the `buttons` options is used", function () {
        it("displays the buttons in the .description element", function () {
          var btnOne, btnTwo, clicked, notification;
          clicked = [];
          lumine.notifications.addSuccess("A message", {
            buttons: [
              {
                text: "Button One",
                className: "btn-one",
                onDidClick: function () {
                  return clicked.push("one");
                },
              },
              {
                text: "Button Two",
                className: "btn-two",
                onDidClick: function () {
                  return clicked.push("two");
                },
              },
            ],
          });
          notification = notificationContainer.querySelector("lumine-notification.success");
          expect(notification).toHaveClass("has-buttons");
          expect(notification.querySelector(".meta")).toBeVisible();
          btnOne = notification.querySelector(".btn-one");
          btnTwo = notification.querySelector(".btn-two");
          expect(btnOne).toHaveClass("btn-success");
          expect(btnOne.textContent).toBe("Button One");
          expect(btnTwo).toHaveClass("btn-success");
          expect(btnTwo.textContent).toBe("Button Two");
          btnTwo.click();
          btnOne.click();
          return expect(clicked).toEqual(["two", "one"]);
        });
        return it("lets a button name its own variant instead of the notification's", function () {
          var accented, plain, notification;
          lumine.notifications.addInfo("A message", {
            buttons: [{ text: "Yes", className: "btn-primary" }, { text: "No" }],
          });
          notification = notificationContainer.querySelector("lumine-notification.info");
          accented = notification.querySelector(".btn-primary");
          plain = notification.querySelectorAll(".btn-toolbar .btn")[1];
          expect(accented.textContent).toBe("Yes");
          expect(accented).not.toHaveClass("btn-info");
          expect(plain.textContent).toBe("No");
          return expect(plain).toHaveClass("btn-info");
        });
      });
      return describe("when an exception is thrown", function () {
        var fatalError, issueBody, issueTitle, ref2;
        ((ref2 = []),
          (notificationContainer = ref2[0]),
          (fatalError = ref2[1]),
          (issueTitle = ref2[2]),
          (issueBody = ref2[3]));
        describe("when the editor is in dev mode", function () {
          beforeEach(function () {
            spyOn(lumine.window, "isDevMode").and.returnValue(true);
            generateException();
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            return (fatalError = notificationContainer.querySelector("lumine-notification.fatal"));
          });
          return it("does not display a notification", function () {
            expect(notificationContainer.childNodes.length).toBe(0);
            return expect(fatalError).toBe(null);
          });
        });
        describe("when the exception has no core or package paths in the stack trace", function () {
          return it("does not display a notification", async () => {
            var handler;
            lumine.notifications.clear();
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            handler = jasmine.createSpy("onWillThrowErrorHandler");
            lumine.runtime.onWillThrowError(handler);
            fs.readFile(__dirname, function () {
              var err;
              err = new Error();
              err.stack =
                "FakeError: foo is not bar\n    at blah.fakeFunc (directory/fakefile.js:1:25)";
              throw err;
            });
            await conditionPromise(() => {
              return handler.calls.count() === 1;
            });
            return expect(lumine.notifications.getNotifications().length).toBe(0);
          });
        });
        describe("when the message contains a newline", function () {
          return it("removes the newline when generating the issue title", async () => {
            var message;
            message =
              "Uncaught Error: Cannot read property 'object' of undefined\nTypeError: Cannot read property 'object' of undefined";
            lumine.notifications.addFatalError(message);
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            fatalError = notificationContainer.querySelector("lumine-notification.fatal");
            await fatalError.getRenderPromise();
            issueTitle = fatalError.issue.getIssueTitle();

            expect(issueTitle).not.toContain("\n");
            return expect(issueTitle).toBe(
              "Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...",
            );
          });
        });
        describe("when the message contains continguous newlines", function () {
          return it("removes the newlines when generating the issue title", async () => {
            var message;
            message = "Uncaught Error: Cannot do the thing\n\nSuper sorry about this";
            lumine.notifications.addFatalError(message);
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            fatalError = notificationContainer.querySelector("lumine-notification.fatal");
            await fatalError.getRenderPromise();
            issueTitle = fatalError.issue.getIssueTitle();

            return expect(issueTitle).toBe(
              "Uncaught Error: Cannot do the thingSuper sorry about this",
            );
          });
        });
        describe("when there are multiple packages in the stack trace", function () {
          beforeEach(function () {
            var detail, stack;
            stack =
              "TypeError: undefined is not a function\n  at Object.module.exports.Pane.promptToSaveItem [as defaultSavePrompt] (/Applications/Lumine.app/Contents/Resources/app/src/pane.js:490:23)\n  at Pane.promptToSaveItem (/Users/someguy/.lumine/packages/save-session/lib/save-prompt.coffee:21:15)\n  at Pane.module.exports.Pane.destroyItem (/Applications/Lumine.app/Contents/Resources/app/src/pane.js:442:18)\n  at HTMLDivElement.<anonymous> (/Applications/Lumine.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)\n  at space-pen-ul.jQuery.event.dispatch (/Applications/Lumine.app/Contents/Resources/app/node_modules/archive-view/node_modules/legacy-views/node_modules/space-pen/vendor/jquery.js:4676:9)\n  at space-pen-ul.elemData.handle (/Applications/Lumine.app/Contents/Resources/app/node_modules/archive-view/node_modules/legacy-views/node_modules/space-pen/vendor/jquery.js:4360:46)";
            detail = "ok";
            lumine.notifications.addFatalError("TypeError: undefined", {
              detail: detail,
              stack: stack,
            });
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            fatalError = notificationContainer.querySelector("lumine-notification.fatal");
            spyOn(fs, "realpathSync").and.callFake(function (p) {
              return p;
            });
            return spyOn(fatalError.issue, "getPackagePathsByPackageName").and.callFake(
              function () {
                return {
                  "save-session": "/Users/someguy/.lumine/packages/save-session",
                  tabs: "/Applications/Lumine.app/Contents/Resources/app/node_modules/tabs",
                };
              },
            );
          });
          return it("chooses the first package in the trace", function () {
            return expect(fatalError.issue.getPackageName()).toBe("save-session");
          });
        });
        describe("when an exception is thrown from a package", function () {
          beforeEach(function () {
            issueTitle = null;
            issueBody = null;
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses();
            spyOn(UserUtils, "getPackageVersionShippedWithLumine").and.callFake(function () {
              return "0.0.0";
            });
            generateException();
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            return (fatalError = notificationContainer.querySelector("lumine-notification.fatal"));
          });
          it("displays a fatal error with the package name in the error", async () => {
            await fatalError.getRenderPromise();
            issueTitle = fatalError.issue.getIssueTitle();
            await fatalError.issue.getIssueBody().then(function (result) {
              return (issueBody = result);
            });

            var button;
            expect(notificationContainer.childNodes.length).toBe(1);
            expect(fatalError).toHaveClass("has-close");
            expect(fatalError.innerHTML).toContain("ReferenceError: a is not defined");
            expect(fatalError.innerHTML).toContain(
              '<a href="https://github.com/lumine-code/notifications">notifications package</a>',
            );
            expect(fatalError.issue.getPackageName()).toBe("notifications");
            button = fatalError.querySelector(".btn");
            expect(button.textContent).toContain("Create issue on the notifications package");
            expect(issueTitle).toContain("$LUMINE_HOME");
            expect(issueTitle).not.toContain(process.env.LUMINE_HOME);
            expect(issueBody).toMatch(/Lumine\*\*: [0-9].[0-9]+.[0-9]+/gi);
            expect(issueBody).not.toMatch(/Unknown/gi);
            expect(issueBody).toContain("ReferenceError: a is not defined");
            expect(issueBody).toContain(
              "Thrown From**: [notifications](https://github.com/lumine-code/notifications) package ",
            );
            return expect(issueBody).toContain("### Non-Core Packages");
          });
          return it("standardizes platform separators on #win32", async () => {
            await fatalError.getRenderPromise();
            issueTitle = fatalError.issue.getIssueTitle();

            expect(issueTitle).toContain(path.posix.sep);
            return expect(issueTitle).not.toContain(path.win32.sep);
          });
        });
        describe("when an exception contains the user's home directory", function () {
          beforeEach(function () {
            var e, errMsg, home;
            issueTitle = null;
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses();
            try {
              // eslint-disable-next-line no-undef -- intentional ReferenceError for the test
              a + 1;
            } catch (error1) {
              e = error1;
              home = process.platform === "win32" ? process.env.USERPROFILE : process.env.HOME;
              errMsg = e.toString() + " in " + home + path.sep + "somewhere";
              window.onerror.call(window, errMsg, "/dev/null", 2, 3, e);
            }
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            return (fatalError = notificationContainer.querySelector("lumine-notification.fatal"));
          });
          return it("replaces the directory with a ~", async () => {
            await fatalError.getRenderPromise();
            issueTitle = fatalError.issue.getIssueTitle();

            expect(issueTitle).toContain("~");
            if (process.platform === "win32") {
              return expect(issueTitle).not.toContain(process.env.USERPROFILE);
            } else {
              return expect(issueTitle).not.toContain(process.env.HOME);
            }
          });
        });
        describe("when an exception is thrown from a linked package", function () {
          beforeEach(function () {
            var detail, message, packageDir, packagesDir, stack;
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses();
            // Resolve the temp directory to its real path: on macOS the temp
            // root is itself a symlink (/var -> /private/var), which would make
            // the package-name lookup miss the realpathed stack frames.
            packagesDir = path.join(
              fs.realpathSync(temp.mkdirSync("lumine-packages-")),
              ".lumine",
              "packages",
            );
            lumine.packages.packageDirPaths.push(packagesDir);
            packageDir = path.join(packagesDir, "..", "..", "github", "linked-package");
            fs.makeTreeSync(path.dirname(path.join(packagesDir, "linked-package")));
            fs.symlinkSync(packageDir, path.join(packagesDir, "linked-package"), "junction");
            fs.writeFileSync(
              path.join(packageDir, "package.json"),
              '{\n  "name": "linked-package",\n  "version": "1.0.0",\n  "repository": "https://github.com/lumine-code/lumine"\n}',
            );
            lumine.packages.enablePackage("linked-package");
            // Build the fake stack from the loaded package's own path — that is
            // the canonical form real crash stacks contain, and the only form
            // guaranteed to match the resolver (on macOS the temp dir has both
            // /var and /private/var spellings).
            var loadedPackagePath = lumine.packages.getLoadedPackage("linked-package").path;
            stack =
              "ReferenceError: path is not defined\n  at Object.module.exports.LinkedPackage.wow (" +
              path.join(loadedPackagePath, "linked-package.coffee") +
              ":29:15)\n  at lumine-workspace.subscriptions.add.lumine.commands.add.linked-package:wow (" +
              path.join(loadedPackagePath, "linked-package.coffee") +
              ":18:102)\n  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Lumine.app/Contents/Resources/app/src/command-registry.js:238:29)\n  at /Applications/Lumine.app/Contents/Resources/app/src/command-registry.js:3:61\n  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Lumine.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:159:32)";
            detail = "At " + path.join(loadedPackagePath, "linked-package.coffee") + ":41";
            message = "Uncaught ReferenceError: path is not defined";
            lumine.notifications.addFatalError(message, {
              stack: stack,
              detail: detail,
              dismissable: true,
            });
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            return (fatalError = notificationContainer.querySelector("lumine-notification.fatal"));
          });
          return it("displays a fatal error with the package name in the error", async () => {
            await fatalError.getRenderPromise();
            expect(notificationContainer.childNodes.length).toBe(1);
            expect(fatalError).toHaveClass("has-close");
            expect(fatalError.innerHTML).toContain("Uncaught ReferenceError: path is not defined");
            expect(fatalError.innerHTML).toContain(
              '<a href="https://github.com/lumine-code/lumine">linked-package package</a>',
            );
            return expect(fatalError.issue.getPackageName()).toBe("linked-package");
          });
        });
        describe("when an exception is thrown from an unloaded package", function () {
          beforeEach(function () {
            var detail, message, packageDir, packagesDir, stack;
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses();
            packagesDir = temp.mkdirSync("lumine-packages-");
            lumine.packages.packageDirPaths.push(path.join(packagesDir, ".lumine", "packages"));
            packageDir = path.join(packagesDir, ".lumine", "packages", "unloaded");
            fs.writeFileSync(
              path.join(packageDir, "package.json"),
              '{\n  "name": "unloaded",\n  "version": "1.0.0",\n  "repository": "https://github.com/lumine-code/lumine"\n}',
            );
            stack = "Error\n  at " + path.join(packageDir, "index.js") + ":1:1";
            detail = "ReferenceError: unloaded error";
            message = "Error";
            lumine.notifications.addFatalError(message, {
              stack: stack,
              detail: detail,
              dismissable: true,
            });
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            return (fatalError = notificationContainer.querySelector("lumine-notification.fatal"));
          });
          return it("displays a fatal error with the package name in the error", async () => {
            await fatalError.getRenderPromise();
            expect(notificationContainer.childNodes.length).toBe(1);
            expect(fatalError).toHaveClass("has-close");
            expect(fatalError.innerHTML).toContain("ReferenceError: unloaded error");
            expect(fatalError.innerHTML).toContain(
              '<a href="https://github.com/lumine-code/lumine">unloaded package</a>',
            );
            return expect(fatalError.issue.getPackageName()).toBe("unloaded");
          });
        });
        describe("when an exception is thrown from a package trying to load", function () {
          beforeEach(function () {
            var detail, message, packageDir, packagesDir, stack;
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses();
            packagesDir = temp.mkdirSync("lumine-packages-");
            lumine.packages.packageDirPaths.push(path.join(packagesDir, ".lumine", "packages"));
            packageDir = path.join(packagesDir, ".lumine", "packages", "broken-load");
            fs.writeFileSync(
              path.join(packageDir, "package.json"),
              '{\n  "name": "broken-load",\n  "version": "1.0.0",\n  "repository": "https://github.com/lumine-code/lumine"\n}',
            );
            stack =
              "TypeError: Cannot read property 'prototype' of undefined\n  at __extends (<anonymous>:1:1)\n  at Object.defineProperty.value [as .coffee] (/Applications/Lumine.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)";
            detail = "TypeError: Cannot read property 'prototype' of undefined";
            message = "Failed to load the broken-load package";
            lumine.notifications.addFatalError(message, {
              stack: stack,
              detail: detail,
              packageName: "broken-load",
              dismissable: true,
            });
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            return (fatalError = notificationContainer.querySelector("lumine-notification.fatal"));
          });
          return it("displays a fatal error with the package name in the error", async () => {
            await fatalError.getRenderPromise();
            expect(notificationContainer.childNodes.length).toBe(1);
            expect(fatalError).toHaveClass("has-close");
            expect(fatalError.innerHTML).toContain(
              "TypeError: Cannot read property 'prototype' of undefined",
            );
            expect(fatalError.innerHTML).toContain(
              '<a href="https://github.com/lumine-code/lumine">broken-load package</a>',
            );
            return expect(fatalError.issue.getPackageName()).toBe("broken-load");
          });
        });
        describe("when an exception is thrown from a package trying to load a grammar", function () {
          beforeEach(function () {
            var detail, message, packageDir, packagesDir, stack;
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses();
            packagesDir = temp.mkdirSync("lumine-packages-");
            lumine.packages.packageDirPaths.push(path.join(packagesDir, ".lumine", "packages"));
            packageDir = path.join(packagesDir, ".lumine", "packages", "language-broken-grammar");
            fs.writeFileSync(
              path.join(packageDir, "package.json"),
              '{\n  "name": "language-broken-grammar",\n  "version": "1.0.0",\n  "repository": "https://github.com/lumine-code/lumine"\n}',
            );
            stack =
              "Unexpected string\n  at nodeTransforms.Literal (/usr/share/lumine/resources/app/node_modules/season/node_modules/cson-parser/lib/parse.js:100:15)\n  at " +
              path.join("packageDir", "grammars", "broken-grammar.cson") +
              ":1:1";
            detail =
              'At Syntax error on line 241, column 18: evalmachine.<anonymous>:1\n"#\\{" "end": "\\}"\n       ^^^^^\nUnexpected string in ' +
              path.join("packageDir", "grammars", "broken-grammar.cson") +
              '\n\nSyntaxError: Syntax error on line 241, column 18: evalmachine.<anonymous>:1\n"#\\{" "end": "\\}"\n       ^^^^^';
            message = "Failed to load a language-broken-grammar package grammar";
            lumine.notifications.addFatalError(message, {
              stack: stack,
              detail: detail,
              packageName: "language-broken-grammar",
              dismissable: true,
            });
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            return (fatalError = notificationContainer.querySelector("lumine-notification.fatal"));
          });
          return it("displays a fatal error with the package name in the error", async () => {
            await fatalError.getRenderPromise();
            expect(notificationContainer.childNodes.length).toBe(1);
            expect(fatalError).toHaveClass("has-close");
            expect(fatalError.innerHTML).toContain(
              "Failed to load a language-broken-grammar package grammar",
            );
            expect(fatalError.innerHTML).toContain(
              '<a href="https://github.com/lumine-code/lumine">language-broken-grammar package</a>',
            );
            return expect(fatalError.issue.getPackageName()).toBe("language-broken-grammar");
          });
        });
        describe("when an exception is thrown from a package trying to activate", function () {
          beforeEach(function () {
            var detail, message, packageDir, packagesDir, stack;
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses();
            packagesDir = temp.mkdirSync("lumine-packages-");
            lumine.packages.packageDirPaths.push(path.join(packagesDir, ".lumine", "packages"));
            packageDir = path.join(packagesDir, ".lumine", "packages", "broken-activation");
            fs.writeFileSync(
              path.join(packageDir, "package.json"),
              '{\n  "name": "broken-activation",\n  "version": "1.0.0",\n  "repository": "https://github.com/lumine-code/lumine"\n}',
            );
            stack =
              "TypeError: Cannot read property 'command' of undefined\n  at Object.module.exports.activate (<anonymous>:7:23)\n  at Package.module.exports.Package.activateNow (/Applications/Lumine.app/Contents/Resources/app.asar/src/package.js:232:19)";
            detail = "TypeError: Cannot read property 'command' of undefined";
            message = "Failed to activate the broken-activation package";
            lumine.notifications.addFatalError(message, {
              stack: stack,
              detail: detail,
              packageName: "broken-activation",
              dismissable: true,
            });
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            return (fatalError = notificationContainer.querySelector("lumine-notification.fatal"));
          });
          return it("displays a fatal error with the package name in the error", async () => {
            await fatalError.getRenderPromise();
            expect(notificationContainer.childNodes.length).toBe(1);
            expect(fatalError).toHaveClass("has-close");
            expect(fatalError.innerHTML).toContain(
              "TypeError: Cannot read property 'command' of undefined",
            );
            expect(fatalError.innerHTML).toContain(
              '<a href="https://github.com/lumine-code/lumine">broken-activation package</a>',
            );
            return expect(fatalError.issue.getPackageName()).toBe("broken-activation");
          });
        });
        describe("when an exception is thrown from a package without a trace, but with a URL", function () {
          // The original spec threw a real ReferenceError and fed its own stack
          // frame in, which only resolved to a package name when this checkout
          // happened to sit under a registered package directory. Registering a
          // package explicitly tests the detection instead of the environment.
          beforeEach(async () => {
            issueBody = null;
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses();

            const packagesDir = temp.mkdirSync("lumine-packages-");
            lumine.packages.packageDirPaths.push(path.join(packagesDir, ".lumine", "packages"));
            const packageDir = path.join(packagesDir, ".lumine", "packages", "url-only");
            fs.writeFileSync(
              path.join(packageDir, "package.json"),
              JSON.stringify({
                name: "url-only",
                version: "1.0.0",
                repository: "https://github.com/lumine-code/lumine",
              }),
            );
            lumine.packages.loadPackage(packageDir);

            const url = path.join(packageDir, "lib", "url-only.js");
            window.onerror.call(window, "ReferenceError: a is not defined", url, 2, 3, {
              message: "ReferenceError: a is not defined",
              stack: void 0,
            });

            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            fatalError = notificationContainer.querySelector("lumine-notification.fatal");
          });

          it("detects the package name from the URL", async () => {
            await fatalError.getRenderPromise();
            expect(fatalError.innerHTML).toContain("ReferenceError: a is not defined");
            expect(fatalError.innerHTML).toContain(
              '<a href="https://github.com/lumine-code/lumine">url-only package</a>',
            );
            expect(fatalError.issue.getPackageName()).toBe("url-only");
          });
        });
        describe("when an exception is thrown from core", function () {
          beforeEach(async () => {
            var e;
            lumine.commands.dispatch(workspaceElement, "some-package:a-command");
            lumine.commands.dispatch(workspaceElement, "some-package:a-command");
            lumine.commands.dispatch(workspaceElement, "some-package:a-command");
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses();
            try {
              // eslint-disable-next-line no-undef -- intentional ReferenceError for the test
              a + 1;
            } catch (error1) {
              e = error1;
              e.stack = e.stack
                .replace(new RegExp(__filename, "g"), "<embedded>")
                .replace(/notifications/g, "core");
              window.onerror.call(window, e.toString(), "/dev/null", 2, 3, e);
            }
            notificationContainer = workspaceElement.querySelector("lumine-notifications");
            fatalError = notificationContainer.querySelector("lumine-notification.fatal");
            await fatalError.getRenderPromise();
            return fatalError.issue.getIssueBody().then(function (result) {
              return (issueBody = result);
            });
          });
          it("displays a fatal error with the package name in the error", function () {
            var button;
            expect(notificationContainer.childNodes.length).toBe(1);
            expect(fatalError).toBeDefined();
            expect(fatalError).toHaveClass("has-close");
            expect(fatalError.innerHTML).toContain("ReferenceError: a is not defined");
            expect(fatalError.innerHTML).toContain("bug in Lumine");
            expect(fatalError.issue.getPackageName()).toBeUndefined();
            button = fatalError.querySelector(".btn");
            expect(button.textContent).toContain("Create issue on lumine-code/lumine");
            expect(issueBody).toContain("ReferenceError: a is not defined");
            return expect(issueBody).toContain("**Thrown From**: Lumine Core");
          });
          it("contains the commands that the user run in the issue body", function () {
            return expect(issueBody).toContain("some-package:a-command");
          });
          return it("allows the user to toggle the stack trace", function () {
            var stackContainer, stackToggle;
            stackToggle = fatalError.querySelector(".stack-toggle");
            stackContainer = fatalError.querySelector(".stack-container");
            expect(stackToggle).toExist();
            expect(stackContainer.style.display).toBe("none");
            stackToggle.click();
            expect(stackContainer.style.display).toBe("block");
            stackToggle.click();
            return expect(stackContainer.style.display).toBe("none");
          });
        });
        describe("when the there is an error searching for the issue", function () {
          beforeEach(async () => {
            spyOn(lumine.window, "isDevMode").and.returnValue(false);
            generateFakeFetchResponses({
              issuesErrorResponse: "403",
            });
            generateException();
            fatalError = notificationContainer.querySelector("lumine-notification.fatal");
            await fatalError.getRenderPromise();
            return (issueBody = fatalError.issue.issueBody);
          });
          return it("asks the user to create an issue", function () {
            var button, fatalNotification;
            button = fatalError.querySelector(".btn");
            fatalNotification = fatalError.querySelector(".fatal-notification");
            expect(button.textContent).toContain("Create issue");
            return expect(fatalNotification.textContent).toContain(
              "The error was thrown from the notifications package.",
            );
          });
        });
        describe("when the error has not been reported", function () {
          beforeEach(function () {
            return spyOn(lumine.window, "isDevMode").and.returnValue(false);
          });
          return describe("when the message is longer than 100 characters", function () {
            var expectedIssueTitle, message;
            message =
              "Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog' at Function.Module._resolveFilename (module.js:351:15) at Function.Module._load (module.js:293:25) at Module.require (module.js:380:17) at EventEmitter.<anonymous> (/Applications/Lumine.app/Contents/Resources/lumine/browser/lib/rpc-server.js:128:79) at EventEmitter.emit (events.js:119:17) at EventEmitter.<anonymous> (/Applications/Lumine.app/Contents/Resources/lumine/browser/api/lib/web-contents.js:99:23) at EventEmitter.emit (events.js:119:17)";
            expectedIssueTitle =
              "Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog' at Function.Module....";
            beforeEach(function () {
              var e;
              generateFakeFetchResponses();
              try {
                // eslint-disable-next-line no-undef -- intentional ReferenceError for the test
                return a + 1;
              } catch (error1) {
                e = error1;
                e.code = "Error";
                e.message = message;
                return window.onerror.call(window, e.message, "abc", 2, 3, e);
              }
            });
            return it("truncates the issue title to 100 characters", async () => {
              fatalError = notificationContainer.querySelector("lumine-notification.fatal");
              await fatalError.getRenderPromise();
              var button;
              button = fatalError.querySelector(".btn");
              expect(button.textContent).toContain("Create issue");
              return expect(fatalError.issue.getIssueTitle()).toBe(expectedIssueTitle);
            });
          });
        });
        describe("when the package is out of date", function () {
          beforeEach(function () {
            var UserUtilities, installedVersion;
            installedVersion = "0.9.0";
            UserUtilities = require("../lib/user-utilities");
            spyOn(UserUtilities, "getPackageVersion").and.callFake(function () {
              return installedVersion;
            });
            return spyOn(lumine.window, "isDevMode").and.returnValue(false);
          });
          // A community package installs from its own Git origin, so nothing here
          // can say whether it is out of date — only a bundled package shadowed by
          // an older local copy reports itself out of date.
          return describe("when the package is a core package", function () {
            describe("when the locally installed version is lower than Lumine's version", function () {
              beforeEach(async () => {
                var UserUtilities, versionShippedWithLumine;
                versionShippedWithLumine = "0.10.0";
                UserUtilities = require("../lib/user-utilities");
                spyOn(UserUtilities, "getPackageVersionShippedWithLumine").and.callFake(
                  function () {
                    return versionShippedWithLumine;
                  },
                );
                generateException();
                fatalError = notificationContainer.querySelector("lumine-notification.fatal");
                await fatalError.getRenderPromise();
                return (issueBody = fatalError.issue.issueBody);
              });
              it("doesn't show the Create Issue button", function () {
                var button;
                button = fatalError.querySelector(".btn-issue");
                return expect(button).not.toExist();
              });
              return it("tells the user that the package is a locally installed core package and out of date", function () {
                var fatalNotification;
                fatalNotification = fatalError.querySelector(".fatal-notification");
                expect(fatalNotification.textContent).toContain(
                  "Locally installed core Lumine package",
                );
                return expect(fatalNotification.textContent).toContain("is out of date");
              });
            });
            return describe("when the locally installed version matches Lumine's version", function () {
              beforeEach(async () => {
                var UserUtilities, versionShippedWithLumine;
                versionShippedWithLumine = "0.9.0";
                UserUtilities = require("../lib/user-utilities");
                spyOn(UserUtilities, "getPackageVersionShippedWithLumine").and.callFake(
                  function () {
                    return versionShippedWithLumine;
                  },
                );
                generateException();
                fatalError = notificationContainer.querySelector("lumine-notification.fatal");
                await fatalError.getRenderPromise();
                return (issueBody = fatalError.issue.issueBody);
              });
              return it("ignores the out of date package because they cant upgrade it without upgrading Lumine", function () {
                var button;
                fatalError = notificationContainer.querySelector("lumine-notification.fatal");
                button = fatalError.querySelector(".btn");
                return expect(button.textContent).toContain("Create issue");
              });
            });
          });
        });
        describe("when the error has been reported", function () {
          beforeEach(function () {
            return spyOn(lumine.window, "isDevMode").and.returnValue(false);
          });
          describe("when the issue is open", function () {
            beforeEach(async () => {
              generateFakeFetchResponses({
                issuesResponse: {
                  items: [
                    {
                      title: "ReferenceError: a is not defined in $LUMINE_HOME/somewhere",
                      html_url: "http://url.com/ok",
                      state: "open",
                    },
                  ],
                },
              });
              spyOn(NotificationIssue.prototype, "getPackageName").and.callFake(function () {
                return "somepackage";
              });
              spyOn(NotificationIssue.prototype, "getRepoUrl").and.callFake(function () {
                return "https://github.com/someguy/somepackage";
              });
              generateException();
              fatalError = notificationContainer.querySelector("lumine-notification.fatal");
              await fatalError.getRenderPromise();
              return (issueBody = fatalError.issue.issueBody);
            });
            return it("shows the user a view issue button", function () {
              var button, fatalNotification;
              fatalNotification = fatalError.querySelector(".fatal-notification");
              button = fatalError.querySelector(".btn");
              expect(button.textContent).toContain("View Issue");
              expect(button.getAttribute("href")).toBe("http://url.com/ok");
              expect(fatalNotification.textContent).toContain("already been reported");
              return expect(fetch.calls.argsFor(0)[0]).toContain(
                encodeURIComponent("someguy/somepackage"),
              );
            });
          });
          return describe("when the issue is closed", function () {
            beforeEach(async () => {
              generateFakeFetchResponses({
                issuesResponse: {
                  items: [
                    {
                      title: "ReferenceError: a is not defined in $LUMINE_HOME/somewhere",
                      html_url: "http://url.com/closed",
                      state: "closed",
                    },
                  ],
                },
              });
              spyOn(NotificationIssue.prototype, "getPackageName").and.callFake(function () {
                return "somepackage";
              });
              spyOn(NotificationIssue.prototype, "getRepoUrl").and.callFake(function () {
                return "https://github.com/someguy/somepackage";
              });
              generateException();
              fatalError = notificationContainer.querySelector("lumine-notification.fatal");
              await fatalError.getRenderPromise();
              return (issueBody = fatalError.issue.issueBody);
            });
            return it("shows the user a view issue button", function () {
              var button;
              button = fatalError.querySelector(".btn");
              expect(button.textContent).toContain("View Issue");
              return expect(button.getAttribute("href")).toBe("http://url.com/closed");
            });
          });
        });
        describe("when a BufferedProcessError is thrown", function () {
          return it("adds an error to the notifications", function () {
            var error;
            expect(notificationContainer.querySelector("lumine-notification.error")).not.toExist();
            window.onerror(
              "Uncaught BufferedProcessError: Failed to spawn command `bad-command`",
              "abc",
              2,
              3,
              {
                name: "BufferedProcessError",
              },
            );
            error = notificationContainer.querySelector("lumine-notification.error");
            expect(error).toExist();
            expect(error.innerHTML).toContain("Failed to spawn command");
            return expect(error.innerHTML).not.toContain("BufferedProcessError");
          });
        });
        return describe("when a spawn ENOENT error is thrown", function () {
          beforeEach(function () {
            return spyOn(lumine.window, "isDevMode").and.returnValue(false);
          });
          describe("when the binary has no path", function () {
            beforeEach(function () {
              var error;
              error = new Error("Error: spawn some_binary ENOENT");
              error.code = "ENOENT";
              return window.onerror.call(window, error.message, "abc", 2, 3, error);
            });
            return it("displays a dismissable error without the stack trace", function () {
              var error;
              notificationContainer = workspaceElement.querySelector("lumine-notifications");
              error = notificationContainer.querySelector("lumine-notification.error");
              return expect(error.textContent).toContain("'some_binary' could not be spawned");
            });
          });
        });
      });
    });
  });
}).call(this);
